In [108]:
import numpy as np
import pandas as pd

The dataset is about the compressive strength of different samples of concrete based on the volumes of the different ingredients that were used to make them. Ingredients include:

1. Cement

2. Blast Furnace Slag

3. Fly Ash

4. Water

5. Superplasticizer

6. Coarse Aggregate

7. Fine Aggregate

Let's read the dataset into a pandas dataframe.

In [109]:
concrete_data = pd.read_csv('concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

checking how many data points we have

In [110]:
concrete_data.shape

(1030, 9)

So, there are approximately 1000 samples of the data.
we have to be careful not to overfit the data due to small samples

In [111]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [112]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

This confirms the data is very clean and is ready to be used to build the model.

Split data into predictors and target

The target variable in this problem is the concrete sample strength. Therefore, our predictors will be all the other columns.

In [113]:
concrete_data_columns = concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [114]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [115]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

normalizing the data by substracting the mean and dividing by the standard deviation

In [116]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [117]:
n_columns=predictors_norm.shape[1]

Now Let's import keras

In [118]:
import keras

In [119]:
from keras.models import Sequential
from keras.layers import Dense

create a  model using the keras

In [120]:
# define regression model
def my_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_columns,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

The above function creates a model that has one hidden layer with 10 neurons and a ReLU activation function. It uses the adam optimizer and the mean squared error as the loss function.

In [121]:
from sklearn.model_selection import train_test_split

In [122]:
 X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.33, random_state=42)

Let's call the function to return the model

In [123]:
# build the model
model = my_model()

In [124]:
#fit the model 
#taking 100epochs
model.fit(X_train,y_train,epochs=100,verbose=1)

Epoch 1/100
22/22 [==============================] - 1s 1ms/step - loss: 1643.2485
Epoch 2/100
22/22 [==============================] - 0s 1ms/step - loss: 1628.2507
Epoch 3/100
22/22 [==============================] - 0s 1ms/step - loss: 1613.2211
Epoch 4/100
22/22 [==============================] - 0s 1ms/step - loss: 1598.2975
Epoch 5/100
22/22 [==============================] - 0s 1ms/step - loss: 1583.3091
Epoch 6/100
22/22 [==============================] - 0s 1ms/step - loss: 1568.0947
Epoch 7/100
22/22 [==============================] - 0s 1ms/step - loss: 1552.6086
Epoch 8/100
22/22 [==============================] - 0s 1ms/step - loss: 1536.6826
Epoch 9/100
22/22 [==============================] - 0s 1ms/step - loss: 1520.1451
Epoch 10/100
22/22 [==============================] - 0s 1ms/step - loss: 1502.9956
Epoch 11/100
22/22 [==============================] - 0s 1ms/step - loss: 1485.5409
Epoch 12/100
22/22 [==============================] - 0s 1ms/step - loss: 1467.1505
Epoch 13/100
22/22 [==============================] - 0s 1ms/step - loss: 1448.4572
Epoch 14/100
22/22 [==============================] - 0s 1ms/step - loss: 1428.7784
Epoch 15/100
22/22 [==============================] - 0s 1ms/step - loss: 1408.2445
Epoch 16/100
22/22 [==============================] - 0s 1ms/step - loss: 1387.2531
Epoch 17/100
22/22 [==============================] - 0s 2ms/step - loss: 1365.2650
Epoch 18/100
22/22 [==============================] - 0s 1ms/step - loss: 1342.6323
Epoch 19/100
22/22 [==============================] - 0s 1ms/step - loss: 1318.8529
Epoch 20/100
22/22 [==============================] - 0s 1ms/step - loss: 1295.1583
Epoch 21/100
22/22 [==============================] - 0s 1ms/step - loss: 1270.0173
Epoch 22/100
22/22 [==============================] - 0s 1ms/step - loss: 1244.6666
Epoch 23/100
22/22 [==============================] - 0s 1ms/step - loss: 1218.3157
Epoch 24/100
22/22 [==============================] - 0s 1ms/step - loss: 1191.6821
Epoch 25/100
22/22 [==============================] - 0s 1ms/step - loss: 1164.7028
Epoch 26/100
22/22 [==============================] - 0s 1ms/step - loss: 1136.8160
Epoch 27/100
22/22 [==============================] - 0s 1ms/step - loss: 1109.0450
Epoch 28/100
22/22 [==============================] - 0s 1ms/step - loss: 1080.5846
Epoch 29/100
22/22 [==============================] - 0s 1ms/step - loss: 1052.3000
Epoch 30/100
22/22 [==============================] - 0s 1ms/step - loss: 1023.5126
Epoch 31/100
22/22 [==============================] - 0s 1ms/step - loss: 995.2767
Epoch 32/100
22/22 [==============================] - 0s 1ms/step - loss: 966.3230
Epoch 33/100
22/22 [==============================] - 0s 1ms/step - loss: 938.0836
Epoch 34/100
22/22 [==============================] - 0s 1ms/step - loss: 909.6959
Epoch 35/100
22/22 [==============================] - 0s 1ms/step - loss: 881.4212
Epoch 36/100
22/22 [==============================] - 0s 1ms/step - loss: 853.4274
Epoch 37/100
22/22 [==============================] - 0s 1ms/step - loss: 825.8257
Epoch 38/100
22/22 [==============================] - 0s 1ms/step - loss: 799.0213
Epoch 39/100
22/22 [==============================] - 0s 1ms/step - loss: 772.0954
Epoch 40/100
22/22 [==============================] - 0s 1ms/step - loss: 745.8065
Epoch 41/100
22/22 [==============================] - 0s 1ms/step - loss: 719.8642
Epoch 42/100
22/22 [==============================] - 0s 1ms/step - loss: 694.7481
Epoch 43/100
22/22 [==============================] - 0s 1ms/step - loss: 670.1616
Epoch 44/100
22/22 [==============================] - 0s 1ms/step - loss: 646.1547
Epoch 45/100
22/22 [==============================] - 0s 1ms/step - loss: 622.4768
Epoch 46/100
22/22 [==============================] - 0s 1ms/step - loss: 599.3656
Epoch 47/100
22/22 [==============================] - 0s 1ms/step - loss: 576.8954
Epoch 48/100
22/22 [==============================] - 0s 1ms/step - loss: 555.1521
Epoch 49/100
22/22 [==============================] - 0s 1ms/step - loss: 533.7545
Epoch 50/100
22/22 [==============================] - 0s 1ms/step - loss: 513.1135
Epoch 51/100
22/22 [==============================] - 0s 1ms/step - loss: 493.1088
Epoch 52/100
22/22 [==============================] - 0s 1ms/step - loss: 473.4164
Epoch 53/100
22/22 [==============================] - 0s 1ms/step - loss: 454.9405
Epoch 54/100
22/22 [==============================] - 0s 1ms/step - loss: 436.9606
Epoch 55/100
22/22 [==============================] - 0s 1ms/step - loss: 419.4385
Epoch 56/100
22/22 [==============================] - 0s 1ms/step - loss: 402.9470
Epoch 57/100
22/22 [==============================] - 0s 3ms/step - loss: 387.5871
Epoch 58/100
22/22 [==============================] - 0s 1ms/step - loss: 372.3393
Epoch 59/100
22/22 [==============================] - 0s 1ms/step - loss: 358.8275
Epoch 60/100
22/22 [==============================] - 0s 1ms/step - loss: 345.4333
Epoch 61/100
22/22 [==============================] - 0s 1ms/step - loss: 333.1617
Epoch 62/100
22/22 [==============================] - 0s 1ms/step - loss: 321.8098
Epoch 63/100
22/22 [==============================] - 0s 1ms/step - loss: 311.1383
Epoch 64/100
22/22 [==============================] - 0s 1ms/step - loss: 300.9389
Epoch 65/100
22/22 [==============================] - 0s 1ms/step - loss: 291.8136
Epoch 66/100
22/22 [==============================] - 0s 1ms/step - loss: 283.0363
Epoch 67/100
22/22 [==============================] - 0s 2ms/step - loss: 275.2157
Epoch 68/100
22/22 [==============================] - 0s 2ms/step - loss: 267.7492
Epoch 69/100
22/22 [==============================] - 0s 1ms/step - loss: 260.9001
Epoch 70/100
22/22 [==============================] - 0s 1ms/step - loss: 254.8166
Epoch 71/100
22/22 [==============================] - 0s 1ms/step - loss: 248.8577
Epoch 72/100
22/22 [==============================] - 0s 2ms/step - loss: 243.6160
Epoch 73/100
22/22 [==============================] - 0s 3ms/step - loss: 238.5442
Epoch 74/100
22/22 [==============================] - 0s 3ms/step - loss: 233.9869
Epoch 75/100
22/22 [==============================] - 0s 3ms/step - loss: 229.7296
Epoch 76/100
22/22 [==============================] - 0s 3ms/step - loss: 225.5264
Epoch 77/100
22/22 [==============================] - 0s 3ms/step - loss: 221.8950
Epoch 78/100
22/22 [==============================] - 0s 3ms/step - loss: 218.3412
Epoch 79/100
22/22 [==============================] - 0s 3ms/step - loss: 214.9281
Epoch 80/100
22/22 [==============================] - 0s 3ms/step - loss: 211.8106
Epoch 81/100
22/22 [==============================] - 0s 3ms/step - loss: 208.7423
Epoch 82/100
22/22 [==============================] - 0s 3ms/step - loss: 206.0976
Epoch 83/100
22/22 [==============================] - 0s 3ms/step - loss: 203.3572
Epoch 84/100
22/22 [==============================] - 0s 3ms/step - loss: 200.9309
Epoch 85/100
22/22 [==============================] - 0s 3ms/step - loss: 198.6011
Epoch 86/100
22/22 [==============================] - 0s 3ms/step - loss: 196.4650
Epoch 87/100
22/22 [==============================] - 0s 3ms/step - loss: 194.2820
Epoch 88/100
22/22 [==============================] - 0s 3ms/step - loss: 192.3319
Epoch 89/100
22/22 [==============================] - 0s 3ms/step - loss: 190.4198
Epoch 90/100
22/22 [==============================] - 0s 3ms/step - loss: 188.5820
Epoch 91/100
22/22 [==============================] - 0s 3ms/step - loss: 186.8665
Epoch 92/100
22/22 [==============================] - 0s 3ms/step - loss: 185.1024
Epoch 93/100
22/22 [==============================] - 0s 3ms/step - loss: 183.5842
Epoch 94/100
22/22 [==============================] - 0s 3ms/step - loss: 181.9391
Epoch 95/100
22/22 [==============================] - 0s 3ms/step - loss: 180.2449
Epoch 96/100
22/22 [==============================] - 0s 3ms/step - loss: 178.7467
Epoch 97/100
22/22 [==============================] - 0s 3ms/step - loss: 177.4173
Epoch 98/100
22/22 [==============================] - 0s 3ms/step - loss: 175.7457
Epoch 99/100
22/22 [==============================] - 0s 3ms/step - loss: 174.2664
Epoch 100/100
22/22 [==============================] - 0s 3ms/step - loss: 172.8229

In [125]:
loss_value=model.evaluate(X_test,y_test)

11/11 [==============================] - 0s 2ms/step - loss: 165.9190

In [126]:
y_pred=model.predict(X_test)

11/11 [==============================] - 0s 2ms/step

In [127]:
loss_value

165.91900634765625

Now we need to compute the mean squared error between the predicted concrete strength and the actual concrete strength.

Let's import the mean_squared_error function from Scikit-learn.

In [128]:
from sklearn.metrics import mean_squared_error
mean_square_error = mean_squared_error(y_test, y_pred)
mean = np.mean(mean_square_error)
standard_deviation = np.std(mean_square_error)
print(mean, standard_deviation)

165.91899543104623 0.0

In [129]:
total_mean_squared_errors = 50
epochs = 100
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')
print("Below is the mean and standard deviation of " +str(total_mean_squared_errors) + " mean squared errors with normalized data. Total number of epochs for each training is: " +str(epochs) + "\n")
print("Mean: "+str(mean))
print("Standard Deviation: "+str(standard_deviation))

MSE 1: 86.60201263427734
10/10 [==============================] - 0s 2ms/step
MSE 2: 84.87020111083984
10/10 [==============================] - 0s 2ms/step
MSE 3: 59.40303421020508
10/10 [==============================] - 0s 2ms/step
MSE 4: 45.2539176940918
10/10 [==============================] - 0s 2ms/step
MSE 5: 43.387203216552734
10/10 [==============================] - 0s 2ms/step
MSE 6: 45.645790100097656
10/10 [==============================] - 0s 2ms/step
MSE 7: 45.529151916503906
10/10 [==============================] - 0s 2ms/step
MSE 8: 34.35477828979492
10/10 [==============================] - 0s 1ms/step
MSE 9: 37.05926513671875
10/10 [==============================] - 0s 2ms/step
MSE 10: 34.282958984375
10/10 [==============================] - 0s 2ms/step
MSE 11: 35.10795974731445
10/10 [==============================] - 0s 2ms/step
MSE 12: 34.02328872680664
10/10 [==============================] - 0s 2ms/step
MSE 13: 39.64291763305664
10/10 [==============================] - 0s 2ms/step
MSE 14: 40.42320251464844
10/10 [==============================] - 0s 3ms/step
MSE 15: 34.72761535644531
10/10 [==============================] - 0s 1ms/step
MSE 16: 30.316362380981445
10/10 [==============================] - 0s 2ms/step
MSE 17: 33.36459732055664
10/10 [==============================] - 0s 1ms/step
MSE 18: 33.49022674560547
10/10 [==============================] - 0s 2ms/step
MSE 19: 32.503414154052734
10/10 [==============================] - 0s 2ms/step
MSE 20: 35.019744873046875
10/10 [==============================] - 0s 1ms/step
MSE 21: 31.332277297973633
10/10 [==============================] - 0s 2ms/step
MSE 22: 31.449724197387695
10/10 [==============================] - 0s 2ms/step
MSE 23: 30.57347297668457
10/10 [==============================] - 0s 2ms/step
MSE 24: 32.537811279296875
10/10 [==============================] - 0s 2ms/step
MSE 25: 33.779640197753906
10/10 [==============================] - 0s 2ms/step
MSE 26: 35.46631622314453
10/10 [==============================] - 0s 2ms/step
MSE 27: 32.5422248840332
10/10 [==============================] - 0s 2ms/step
MSE 28: 31.850296020507812
10/10 [==============================] - 0s 2ms/step
MSE 29: 36.312721252441406
10/10 [==============================] - 0s 2ms/step
MSE 30: 36.71879577636719
10/10 [==============================] - 0s 2ms/step
MSE 31: 33.277992248535156
10/10 [==============================] - 0s 2ms/step
MSE 32: 31.951913833618164
10/10 [==============================] - 0s 1ms/step
MSE 33: 32.22233200073242
10/10 [==============================] - 0s 1ms/step
MSE 34: 35.550514221191406
10/10 [==============================] - 0s 2ms/step
MSE 35: 35.233943939208984
10/10 [==============================] - 0s 2ms/step
MSE 36: 41.007022857666016
10/10 [==============================] - 0s 2ms/step
MSE 37: 30.388132095336914
10/10 [==============================] - 0s 2ms/step
MSE 38: 36.128047943115234
10/10 [==============================] - 0s 3ms/step
MSE 39: 33.12238693237305
10/10 [==============================] - 0s 2ms/step
MSE 40: 29.92984962463379
10/10 [==============================] - 0s 2ms/step
MSE 41: 35.10951232910156
10/10 [==============================] - 0s 2ms/step
MSE 42: 29.103443145751953
10/10 [==============================] - 0s 2ms/step
MSE 43: 33.829307556152344
10/10 [==============================] - 0s 2ms/step
MSE 44: 34.91554641723633
10/10 [==============================] - 0s 1ms/step
MSE 45: 37.691505432128906
10/10 [==============================] - 0s 2ms/step
MSE 46: 33.87068176269531
10/10 [==============================] - 0s 853us/step
MSE 47: 32.3963737487793
10/10 [==============================] - 0s 1ms/step
MSE 48: 34.03175735473633
10/10 [==============================] - 0s 2ms/step
MSE 49: 34.977352142333984
10/10 [==============================] - 0s 2ms/step
MSE 50: 36.00053787231445
10/10 [==============================] - 0s 2ms/step


Below is the mean and standard deviation of 50 mean squared errors with normalized data. Total number of epochs for each training is: 100

Mean: 37.566181693091586
Standard Deviation: 11.08302956349885