In [138]:
import numpy as np
import pandas as pd

The dataset is about the compressive strength of different samples of concrete based on the volumes of the different ingredients that were used to make them. Ingredients include:

1. Cement

2. Blast Furnace Slag

3. Fly Ash

4. Water

5. Superplasticizer

6. Coarse Aggregate

7. Fine Aggregate

Let's read the dataset into a pandas dataframe.

In [139]:
concrete_data = pd.read_csv('concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

checking how many data points we have

In [140]:
concrete_data.shape

(1030, 9)

So, there are approximately 1000 samples of the data.
we have to be careful not to overfit the data due to small samples

In [141]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [142]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

This confirms the data is very clean and is ready to be used to build the model.

Split data into predictors and target

The target variable in this problem is the concrete sample strength. Therefore, our predictors will be all the other columns.

In [143]:
concrete_data_columns = concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [144]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [145]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

normalizing the data by substracting the mean and dividing by the standard deviation

In [146]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [147]:
n_columns=predictors_norm.shape[1]

Now Let's import keras

In [148]:
import keras

In [149]:
from keras.models import Sequential
from keras.layers import Dense

create a  model using the keras

In [150]:
# define regression model
def my_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_columns,)))
    model.add(Dense(10,activation='relu'))
    model.add(Dense(10,activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

The above function creates a model that has one hidden layer with 10 neurons and a ReLU activation function. It uses the adam optimizer and the mean squared error as the loss function.

In [151]:
from sklearn.model_selection import train_test_split

In [152]:
 X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.33, random_state=42)

Let's call the function to return the model

In [153]:
# build the model
model = my_model()

In [154]:
#fit the model 
#taking 50pochs
model.fit(X_train,y_train,epochs=100,verbose=1)

Epoch 1/100
22/22 [==============================] - 1s 2ms/step - loss: 1629.3335
Epoch 2/100
22/22 [==============================] - 0s 1ms/step - loss: 1589.6174
Epoch 3/100
22/22 [==============================] - 0s 1ms/step - loss: 1554.0034
Epoch 4/100
22/22 [==============================] - 0s 1ms/step - loss: 1515.2701
Epoch 5/100
22/22 [==============================] - 0s 1ms/step - loss: 1466.0751
Epoch 6/100
22/22 [==============================] - 0s 1ms/step - loss: 1399.6443
Epoch 7/100
22/22 [==============================] - 0s 2ms/step - loss: 1302.1726
Epoch 8/100
22/22 [==============================] - 0s 1ms/step - loss: 1170.0222
Epoch 9/100
22/22 [==============================] - 0s 1ms/step - loss: 993.1823
Epoch 10/100
22/22 [==============================] - 0s 2ms/step - loss: 778.4861
Epoch 11/100
22/22 [==============================] - 0s 1ms/step - loss: 570.0643
Epoch 12/100
22/22 [==============================] - 0s 1ms/step - loss: 407.0852
Epoch 13/100
22/22 [==============================] - 0s 1ms/step - loss: 315.3707
Epoch 14/100
22/22 [==============================] - 0s 1ms/step - loss: 272.4232
Epoch 15/100
22/22 [==============================] - 0s 1ms/step - loss: 248.8869
Epoch 16/100
22/22 [==============================] - 0s 1ms/step - loss: 234.3720
Epoch 17/100
22/22 [==============================] - 0s 1ms/step - loss: 222.9252
Epoch 18/100
22/22 [==============================] - 0s 1ms/step - loss: 213.0605
Epoch 19/100
22/22 [==============================] - 0s 1ms/step - loss: 205.1693
Epoch 20/100
22/22 [==============================] - 0s 1ms/step - loss: 197.7507
Epoch 21/100
22/22 [==============================] - 0s 1ms/step - loss: 191.6640
Epoch 22/100
22/22 [==============================] - 0s 2ms/step - loss: 185.8945
Epoch 23/100
22/22 [==============================] - 0s 1ms/step - loss: 180.8550
Epoch 24/100
22/22 [==============================] - 0s 2ms/step - loss: 175.7107
Epoch 25/100
22/22 [==============================] - 0s 1ms/step - loss: 170.8938
Epoch 26/100
22/22 [==============================] - 0s 1ms/step - loss: 166.5732
Epoch 27/100
22/22 [==============================] - 0s 1ms/step - loss: 162.3519
Epoch 28/100
22/22 [==============================] - 0s 1ms/step - loss: 158.0948
Epoch 29/100
22/22 [==============================] - 0s 1ms/step - loss: 153.8666
Epoch 30/100
22/22 [==============================] - 0s 1ms/step - loss: 149.9272
Epoch 31/100
22/22 [==============================] - 0s 1ms/step - loss: 146.1625
Epoch 32/100
22/22 [==============================] - 0s 1ms/step - loss: 141.8551
Epoch 33/100
22/22 [==============================] - 0s 1ms/step - loss: 138.2043
Epoch 34/100
22/22 [==============================] - 0s 3ms/step - loss: 134.8983
Epoch 35/100
22/22 [==============================] - 0s 1ms/step - loss: 131.5997
Epoch 36/100
22/22 [==============================] - 0s 1ms/step - loss: 128.3698
Epoch 37/100
22/22 [==============================] - 0s 1ms/step - loss: 125.1126
Epoch 38/100
22/22 [==============================] - 0s 1ms/step - loss: 122.2277
Epoch 39/100
22/22 [==============================] - 0s 1ms/step - loss: 119.4266
Epoch 40/100
22/22 [==============================] - 0s 1ms/step - loss: 116.9741
Epoch 41/100
22/22 [==============================] - 0s 1ms/step - loss: 113.7537
Epoch 42/100
22/22 [==============================] - 0s 1ms/step - loss: 111.3545
Epoch 43/100
22/22 [==============================] - 0s 1ms/step - loss: 109.0563
Epoch 44/100
22/22 [==============================] - 0s 1ms/step - loss: 106.6190
Epoch 45/100
22/22 [==============================] - 0s 1ms/step - loss: 104.2047
Epoch 46/100
22/22 [==============================] - 0s 1ms/step - loss: 102.4268
Epoch 47/100
22/22 [==============================] - 0s 1ms/step - loss: 99.9533
Epoch 48/100
22/22 [==============================] - 0s 1ms/step - loss: 98.1451
Epoch 49/100
22/22 [==============================] - 0s 2ms/step - loss: 95.9768
Epoch 50/100
22/22 [==============================] - 0s 2ms/step - loss: 94.1504
Epoch 51/100
22/22 [==============================] - 0s 1ms/step - loss: 92.5436
Epoch 52/100
22/22 [==============================] - 0s 1ms/step - loss: 90.6797
Epoch 53/100
22/22 [==============================] - 0s 1ms/step - loss: 89.0687
Epoch 54/100
22/22 [==============================] - 0s 1ms/step - loss: 87.4275
Epoch 55/100
22/22 [==============================] - 0s 1ms/step - loss: 85.7451
Epoch 56/100
22/22 [==============================] - 0s 1ms/step - loss: 83.9943
Epoch 57/100
22/22 [==============================] - 0s 1ms/step - loss: 82.5253
Epoch 58/100
22/22 [==============================] - 0s 1ms/step - loss: 81.3202
Epoch 59/100
22/22 [==============================] - 0s 1ms/step - loss: 80.0041
Epoch 60/100
22/22 [==============================] - 0s 1ms/step - loss: 78.5784
Epoch 61/100
22/22 [==============================] - 0s 1ms/step - loss: 77.3159
Epoch 62/100
22/22 [==============================] - 0s 1ms/step - loss: 75.7097
Epoch 63/100
22/22 [==============================] - 0s 1ms/step - loss: 74.6965
Epoch 64/100
22/22 [==============================] - 0s 1ms/step - loss: 73.4806
Epoch 65/100
22/22 [==============================] - 0s 1ms/step - loss: 72.3309
Epoch 66/100
22/22 [==============================] - 0s 1ms/step - loss: 71.2139
Epoch 67/100
22/22 [==============================] - 0s 1ms/step - loss: 70.1651
Epoch 68/100
22/22 [==============================] - 0s 1ms/step - loss: 69.2587
Epoch 69/100
22/22 [==============================] - 0s 1ms/step - loss: 67.9684
Epoch 70/100
22/22 [==============================] - 0s 1ms/step - loss: 67.1823
Epoch 71/100
22/22 [==============================] - 0s 1ms/step - loss: 66.3857
Epoch 72/100
22/22 [==============================] - 0s 1ms/step - loss: 65.5434
Epoch 73/100
22/22 [==============================] - 0s 1ms/step - loss: 64.3975
Epoch 74/100
22/22 [==============================] - 0s 1ms/step - loss: 63.5986
Epoch 75/100
22/22 [==============================] - 0s 2ms/step - loss: 62.4337
Epoch 76/100
22/22 [==============================] - 0s 3ms/step - loss: 61.4257
Epoch 77/100
22/22 [==============================] - 0s 3ms/step - loss: 60.4188
Epoch 78/100
22/22 [==============================] - 0s 4ms/step - loss: 59.5634
Epoch 79/100
22/22 [==============================] - 0s 3ms/step - loss: 58.9769
Epoch 80/100
22/22 [==============================] - 0s 3ms/step - loss: 57.7051
Epoch 81/100
22/22 [==============================] - 0s 3ms/step - loss: 57.1163
Epoch 82/100
22/22 [==============================] - 0s 3ms/step - loss: 56.2471
Epoch 83/100
22/22 [==============================] - 0s 3ms/step - loss: 55.0678
Epoch 84/100
22/22 [==============================] - 0s 3ms/step - loss: 54.4349
Epoch 85/100
22/22 [==============================] - 0s 3ms/step - loss: 53.6715
Epoch 86/100
22/22 [==============================] - 0s 3ms/step - loss: 53.0742
Epoch 87/100
22/22 [==============================] - 0s 3ms/step - loss: 52.4535
Epoch 88/100
22/22 [==============================] - 0s 3ms/step - loss: 52.1382
Epoch 89/100
22/22 [==============================] - 0s 3ms/step - loss: 51.8250
Epoch 90/100
22/22 [==============================] - 0s 3ms/step - loss: 51.3223
Epoch 91/100
22/22 [==============================] - 0s 3ms/step - loss: 50.8874
Epoch 92/100
22/22 [==============================] - 0s 3ms/step - loss: 50.4752
Epoch 93/100
22/22 [==============================] - 0s 3ms/step - loss: 49.9452
Epoch 94/100
22/22 [==============================] - 0s 3ms/step - loss: 49.4839
Epoch 95/100
22/22 [==============================] - 0s 3ms/step - loss: 49.1743
Epoch 96/100
22/22 [==============================] - 0s 3ms/step - loss: 48.7818
Epoch 97/100
22/22 [==============================] - 0s 3ms/step - loss: 48.6678
Epoch 98/100
22/22 [==============================] - 0s 3ms/step - loss: 48.2783
Epoch 99/100
22/22 [==============================] - 0s 3ms/step - loss: 47.8510
Epoch 100/100
22/22 [==============================] - 0s 3ms/step - loss: 47.6331

In [155]:
loss_value=model.evaluate(X_test,y_test)

11/11 [==============================] - 0s 2ms/step - loss: 52.7542

In [156]:
y_pred=model.predict(X_test)

11/11 [==============================] - 0s 2ms/step

In [157]:
loss_value

52.75422668457031

Now we need to compute the mean squared error between the predicted concrete strength and the actual concrete strength.

Let's import the mean_squared_error function from Scikit-learn.

In [158]:
from sklearn.metrics import mean_squared_error
mean_square_error = mean_squared_error(y_test, y_pred)
mean = np.mean(mean_square_error)
standard_deviation = np.std(mean_square_error)
print(mean, standard_deviation)

52.75423165911037 0.0

In [159]:
total_mean_squared_errors = 50
epochs = 50
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')
print("Below is the mean and standard deviation of " +str(total_mean_squared_errors) + " mean squared errors with normalized data. Total number of epochs for each training is: " +str(epochs) + "\n")
print("Mean: "+str(mean))
print("Standard Deviation: "+str(standard_deviation))

MSE 1: 47.500858306884766
10/10 [==============================] - 0s 2ms/step
MSE 2: 48.79554748535156
10/10 [==============================] - 0s 2ms/step
MSE 3: 35.53360366821289
10/10 [==============================] - 0s 1ms/step
MSE 4: 32.97996139526367
10/10 [==============================] - 0s 3ms/step
MSE 5: 32.78551483154297
10/10 [==============================] - 0s 2ms/step
MSE 6: 36.3907356262207
10/10 [==============================] - 0s 2ms/step
MSE 7: 35.70600128173828
10/10 [==============================] - 0s 1ms/step
MSE 8: 27.901029586791992
10/10 [==============================] - 0s 2ms/step
MSE 9: 29.96082305908203
10/10 [==============================] - 0s 2ms/step
MSE 10: 30.80217170715332
10/10 [==============================] - 0s 2ms/step
MSE 11: 29.035234451293945
10/10 [==============================] - 0s 2ms/step
MSE 12: 25.104232788085938
10/10 [==============================] - 0s 2ms/step
MSE 13: 30.000585556030273
10/10 [==============================] - 0s 2ms/step
MSE 14: 30.36652374267578
10/10 [==============================] - 0s 3ms/step
MSE 15: 25.24359893798828
10/10 [==============================] - 0s 2ms/step
MSE 16: 21.594621658325195
10/10 [==============================] - 0s 2ms/step
MSE 17: 24.28855323791504
10/10 [==============================] - 0s 2ms/step
MSE 18: 25.249629974365234
10/10 [==============================] - 0s 2ms/step
MSE 19: 21.872770309448242
10/10 [==============================] - 0s 2ms/step
MSE 20: 25.66525650024414
10/10 [==============================] - 0s 3ms/step
MSE 21: 21.071380615234375
10/10 [==============================] - 0s 3ms/step
MSE 22: 23.347116470336914
10/10 [==============================] - 0s 1ms/step
MSE 23: 20.306106567382812
10/10 [==============================] - 0s 2ms/step
MSE 24: 24.342796325683594
10/10 [==============================] - 0s 2ms/step
MSE 25: 24.63687515258789
10/10 [==============================] - 0s 2ms/step
MSE 26: 27.229333877563477
10/10 [==============================] - 0s 2ms/step
MSE 27: 24.055166244506836
10/10 [==============================] - 0s 2ms/step
MSE 28: 23.972196578979492
10/10 [==============================] - 0s 2ms/step
MSE 29: 25.32384490966797
10/10 [==============================] - 0s 1ms/step
MSE 30: 21.38080596923828
10/10 [==============================] - 0s 2ms/step
MSE 31: 22.534212112426758
10/10 [==============================] - 0s 2ms/step
MSE 32: 17.868864059448242
10/10 [==============================] - 0s 2ms/step
MSE 33: 18.989521026611328
10/10 [==============================] - 0s 2ms/step
MSE 34: 24.390182495117188
10/10 [==============================] - 0s 2ms/step
MSE 35: 22.726287841796875
10/10 [==============================] - 0s 2ms/step
MSE 36: 28.759986877441406
10/10 [==============================] - 0s 2ms/step
MSE 37: 19.027122497558594
10/10 [==============================] - 0s 2ms/step
MSE 38: 24.470661163330078
10/10 [==============================] - 0s 2ms/step
MSE 39: 23.26362419128418
10/10 [==============================] - 0s 2ms/step
MSE 40: 17.144895553588867
10/10 [==============================] - 0s 3ms/step
MSE 41: 21.736330032348633
10/10 [==============================] - 0s 2ms/step
MSE 42: 19.60724449157715
10/10 [==============================] - 0s 2ms/step
MSE 43: 19.935882568359375
10/10 [==============================] - 0s 2ms/step
MSE 44: 24.69472312927246
10/10 [==============================] - 0s 2ms/step
MSE 45: 25.879003524780273
10/10 [==============================] - 0s 2ms/step
MSE 46: 19.948833465576172
10/10 [==============================] - 0s 2ms/step
MSE 47: 21.919824600219727
10/10 [==============================] - 0s 2ms/step
MSE 48: 20.31060218811035
10/10 [==============================] - 0s 3ms/step
MSE 49: 22.171354293823242
10/10 [==============================] - 0s 2ms/step
MSE 50: 21.52025032043457
10/10 [==============================] - 0s 1ms/step


Below is the mean and standard deviation of 50 mean squared errors with normalized data. Total number of epochs for each training is: 50

Mean: 25.786845482679386
Standard Deviation: 6.4777440207211345